# Site
title: cbh
description: sola dosis facit venenum
url: https://cbeauhilton.github.io/
locale: en_US
# Site logo
logo: arsenic_logo_300.svg

future: true

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed
show_drafts: false

# Google Analytics
google-analytics: UA-124056131-1

# Social Links
email:             cbeauhilton@gmail.com
#google.plus:        username
twitter:            beauhilton
#facebook:           username
github:             cbeauhilton
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems are now called plugins
plugins:
  - jekyll
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-scholar
#  - jekyll-scholar-extras
#  - jekyll-pandoc-multiple-formats
  - liquid_reading_time
  - nokogiri

# Exclude list
include:
  - .nojekyll
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - jekgit.sh
